version: '3.3'
services:
  postgres:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=sonar
      - POSTGRES_PASSWORD=sonar
    volumes:
      - /opt/sonar/:/opt/prstgress
  SonarQube:
    image: sonarqube
    ports:
      - "9000:9000"
    volumes:
      - /opt/sonar/:/opt/sonar
    environment:
      - SONARQUBE_JDBC_USERNAME=sonar
      - SONARQUBE_JDBC_PASSWORD=sonar
      - SONARQUBE_JDBC_URL=jdbc:postgresql://postgres:5432/sonar
    depends_on:
      - postgres
  tomcat:
    build: .
    image: tomcat:1.1
    volumes:
      - /root/Sample_Project/target/:/usr/local/tomcat/webapps
    ports:
      - "8086:8080"
  jenkins:
    image: jenkins
    ports:
      - "8080:8080"
    volumes:
      - /opt/sonar:/opt/jenkins
