version: '3.7'
services:
  mysql:
    image: mysql
    ports:
      - "3306:3306"
    environment:
      - MYSQL_DATABASE=suresh
      - MYSQL_ROOT_PASSWORD=123
    volumes:
    - /opt/sonar:/opt/mysql
  jenkins:
    image: jenkins
    ports:
      - "8083:8080"
    environment:
      - a=20
    volumes:
      - /opt/sonar:/opt/jenkins
    depends_on:
      - mysql
      
networks:
  - own
  
